version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - node
    restart: always

  node:
    image: node:18
    working_dir: /app/back
    command: sh -c "npm install && npm run start"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./back/.env

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: casp2najanongbaw
      MYSQL_DATABASE: casp2-demo
    volumes:
      - ./back/db/database.sql:/docker-entrypoint-initdb.d/database.sql